version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: fyn-scheduler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  scheduler:
    build: .
    container_name: fyn-scheduler
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FYNS_FOLDER=/app/fyns
      - GIT_ENABLED=true
      - LOG_LEVEL=info
    volumes:
      - ./fyns:/app/fyns
      - ./logs:/app/logs
      - fyn_node_modules:/app/fyns/node_modules
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
  fyn_node_modules: